[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W"]        # pycodestyle/pyflakes warnings & errors
ignore = ["E203"]               # Keep Black-compatible

[tool.ruff.format]
quote-style = "double"
