# Generated by Django 4.2.24 on 2025-10-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='better_bill_project.client')),
            ],
            options={
                'ordering': ['matter_number'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['initials'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activity_code', models.CharField(blank=True, max_length=50)),
                ('narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_earner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='better_bill_project.personnel')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='better_bill_project.matter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='lead_fee_earner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_matters', to='better_bill_project.personnel'),
        ),
    ]
