# Generated by Django 4.2.24 on 2025-10-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0003_alter_personnel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role']},
        ),
        migrations.AddField(
            model_name='personnel',
            name='role_text',
            field=models.CharField(blank=True, db_column='role', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='better_bill_project.role'),
        ),
    ]
