# Generated by Django 4.2.24 on 2025-10-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0004_alter_role_options_personnel_role_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='role_text',
        ),
    ]
