# Generated by Django 4.2.24 on 2025-10-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0005_remove_personnel_role_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='better_bill_project.role'),
        ),
    ]
