# Generated by Django 4.2.24 on 2025-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0007_alter_personnel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
