# Generated by Django 4.2.24 on 2025-10-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0008_alter_client_client_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=50, unique=True)),
                ('activity_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Activity Code',
                'verbose_name_plural': 'Activity Codes',
                'ordering': ['activity_code'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='matter',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='activity_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='better_bill_project.activitycode'),
        ),
    ]
