# Generated by Django 4.2.24 on 2025-10-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0009_activitycode_alter_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='client',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
