# Generated by Django 4.2.24 on 2025-10-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0010_remove_client_address_client_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='personnel_rate',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, help_text='Time worked, in 0.1-hour increments (6 minutes)', max_digits=5),
        ),
    ]
