# Generated by Django 4.2.24 on 2025-10-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0011_remove_timeentry_personnel_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=5)),
                ('narrative', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed'), ('written_off', 'Written off')], default='unbilled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wip_items', to='better_bill_project.activitycode')),
                ('fee_earner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_items', to='better_bill_project.personnel')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_items', to='better_bill_project.matter')),
                ('time_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wip', to='better_bill_project.timeentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
