# Generated by Django 4.2.24 on 2025-10-13 21:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0012_wip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='better_bill_project.client')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='better_bill_project.matter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
    database_operations=[
        # DB column already exists → do nothing here
    ],
    state_operations=[
        migrations.AddField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(
                blank=True, null=True,  # keep current nullability
                on_delete=django.db.models.deletion.PROTECT,
                related_name='time_entries',
                to='better_bill_project.client',
            ),
        ),
    ],
),

        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='better_bill_project.client')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='better_bill_project.invoice')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='better_bill_project.matter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Snapshot of rate at invoice time', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='better_bill_project.invoice')),
                ('wip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_lines', to='better_bill_project.wip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
