# Generated by Django 4.2.24 on 2025-10-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0013_invoice_timeentry_client_ledger_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='better_bill_project.matter'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='activity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='better_bill_project.activitycode'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='better_bill_project.client'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='narrative',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wip',
            name='activity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_items', to='better_bill_project.activitycode'),
        ),
        migrations.AlterField(
            model_name='wip',
            name='narrative',
            field=models.TextField(),
        ),
    ]
