# Generated by Django 4.2.24 on 2025-10-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0014_alter_invoice_matter_alter_invoiceline_desc_and_more'),
    ]

    operations = [
    ]
