# Generated by Django 4.2.24 on 2025-10-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0017_alter_wip_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wip',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='better_bill_project.client'),
        ),
    ]
