# Generated by Django 4.2.24 on 2025-10-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0019_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, help_text='Time worked, in 0.1-hour increments', max_digits=5),
        ),
    ]
