# Generated by Django 4.2.24 on 2025-10-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0020_alter_ledger_status_alter_timeentry_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
