# Generated by Django 4.2.24 on 2025-10-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0021_ledger_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='better_bill_project.personnel'),
        ),
    ]
