# Generated by Django 4.2.24 on 2025-10-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_bill_project', '0022_personnel_line_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='line_manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__role__in', ('Partner', 'Associate Partner'))), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='better_bill_project.personnel'),
        ),
    ]
